extends:
  - stylelint-config-recommended
  - stylelint-config-recommended-scss
  - stylelint-config-html/astro
  - stylelint-config-prettier-scss
plugins:
  - stylelint-scss
rules:
  string-quotes: single
  scss/at-rule-no-unknown: null
